### ISSUE TITLE
[BUG] Lag when moving the pane with finger

### ISSUE THREAD

**Issue by corentin-gautier** [roman-rr/cupertino-pane#56]
**Describe the bug**
There is a huge lag when moving the pane around using a finger. Moving the pane by swiping up to trigger the animation to the next breakpoint doesn't have the same issue, it only happens when keeping your finger down and moving around

**Screenshot**
https://drive.google.com/file/d/1iEeYl0uPSIczpAgUxxlY8bioa-tYROGn/view?usp=sharing

**To Reproduce**
1. go to the example pages on a mobile device
2. move the pane up and down with a finger

**Smartphone (please complete the following information):**
 - Device: Oneplus 6
 - OS: Android
 - Browser Ionic (WebView)

**Comment by roman-rr** [comment]
@corentin-gautier Big thanks for report. seems that is something Android related. 
Could you try please with iOS if you are able ?

**Comment by corentin-gautier** [comment]
@roman-rr I will try tomorrow on IOS

( Also I forgot : Very nive work on this component ;) )

**Comment by marcofugaro** [comment]
Yup, confirmed this happens on latest Chrome for Android

**Comment by roman-rr** [comment]
Should be fixed with `1.1.81`

**Comment by marcofugaro** [comment]
@roman-rr I've tried the `Base live` jsbin on my phone and the problem persists. It should be already using the `1.1.81 version`

**Comment by roman-rr** [comment]
@marcofugaro jsbin save cache for awhile. But i will re-check.

**Comment by corentin-gautier** [comment]
@roman-rr I'm still having the issue with 1.1.81. Here's a little bit of additionnal information : the bug doesn't happen when the navigator console is open

**Comment by roman-rr** [comment]
@corentin-gautier @marcofugaro 
Related recent chromium [issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1123304)
Decided to await 3-5 days, maybe quick proper solution will be founded by chromium developers. 
Otherwise i will found how to handle on our side with some event hack.

**Comment by PickRelated** [comment]
@roman-rr this is not a new issue. It exists since 2014. I was really surprised to face it myself. I've made a PR #60 that should fix this issue. Please try it for yourself.

**Comment by roman-rr** [comment]
Issue still doesn't fixed on chrome side for 2 weeks. Create patch, Pushed `1.1.82`.

**Comment by marcofugaro** [comment]
Works like a charm now 🎉
